BEGIN;

USE library;


INSERT INTO authors_simple (full_name) VALUES
	(' BBC'),
	(' Braithwaite'),
	(' Kautiyla'),
	(' Machiavelli'),
	(' Nariman'),
	(' Palkhivala'),
	(' Sebastian Gutierrez'),
	(' Sorabjee'),
	(' Various'),
	('Abraham Eraly'),
	('Adam Smith'),
	('Albert Camus'),
	('Aldous Huxley'),
	('Alex Rutherford'),
	('Alfred Stonier'),
	('Allen Downey'),
	('Amartya Sen'),
	('Amir Aczel'),
	('Amitav Ghosh'),
	('Andrew Tanenbaum'),
	('Andy Oram'),
	('Arthur Conan Doyle'),
	('Ayn Rand'),
	('Bertrand Russell'),
	('Bob Dylan'),
	('Bob Woodward'),
	('Carl Sagan'),
	('Cedric Villani'),
	('Charles Dickens'),
	('Dan Brown'),
	('David Bodanis'),
	('David Forsyth'),
	('Dominique Lapierre'),
	('Drew Conway'),
	('E T Bell'),
	('Earle Stanley Gardner'),
	('Edgar Allen Poe'),
	('Edward Said'),
	('Eric Raymond'),
	('Ernest Hemingway'),
	('Frank Kafka'),
	('Frank Shih'),
	('Frederick Forsyth'),
	('Fritjof Capra'),
	('Fyodor Dostoevsky'),
	('Gary Bradsky'),
	('George Orwell'),
	('Gerald Durrell'),
	('Gerald Sussman'),
	('H G Wells'),
	('Hart Duda'),
	('Hussain Zaidi'),
	('J K Rowling'),
	('Jaideva Goswami'),
	('James Gleick'),
	('Jawaharlal Nehru'),
	('Jean Sassoon'),
	('Jeffery Archer'),
	('Jim Corbett'),
	('John Foreman'),
	('John Grisham'),
	('John Pratt'),
	('John Steinbeck'),
	('Jonathan Stroud'),
	('Joseph Heller'),
	('Joy Thomas'),
	('Jules Verne'),
	('Keith Devlin'),
	('Ken Follett'),
	('Kuldip Nayar'),
	('Kurt Vonnegut'),
	('Lee Iacoca'),
	('Leonard Mlodinow'),
	('Lorraine Hansberry'),
	('Madan Gupta'),
	('Maria Konnikova'),
	('Michael Baz-Zohar'),
	('Michael Crichton'),
	('Morris West'),
	('Muhammad Rashid'),
	('Nate Silver'),
	('Ned Mohan'),
	('P L Deshpande'),
	('Peter Ackroyd'),
	('Peter Dickinson'),
	('Peter Drucker'),
	('Phillip Janert'),
	('Randy Pausch'),
	('Richard Bach'),
	('Richard Dawkins'),
	('Richard Feynman'),
	('Richard Gordon'),
	('Robert Fisk'),
	('Robert Nisbet'),
	('Robert Pirsig'),
	('Sam Harris'),
	('Samuel Huntington'),
	('Sanjay Garg'),
	('Schilling Taub'),
	('Sergio Franco'),
	('Shashi Tharoor'),
	('Siddhartha Deb'),
	('Simon Haykin'),
	('Simon Singh'),
	('Steig Larsson'),
	('Stephen Dubner'),
	('Stephen Hawking'),
	('Steve Eddins'),
	('Sudhanshu Ranjan'),
	('Sunita Deshpande'),
	('Terence Tao'),
	('Thomas Cormen'),
	('Thomas Friedman'),
	('V P Kale'),
	('V P Menon'),
	('V S Naipaul'),
	('Victor Hugo'),
	('Vladimir Vapnik'),
	('W. H. Greene'),
	('Werner Heisenberg'),
	('Wes McKinney'),
	('Will Durant'),
	('William Dalrymple'),
	('William S Maugham'),
	('Yashwant Kanetkar')
;

COMMIT;

