BEGIN;

USE library;


INSERT INTO authors_simple (full_name) VALUES
	('Peter Ackroyd'),
	('Amir Aczel'),
	('Jeffery Archer'),
	('Richard Bach'),
	('Michael Baz-Zohar'),
	(' BBC'),
	('E T Bell'),
	('David Bodanis'),
	('Gary Bradsky'),
	(' Braithwaite'),
	('Dan Brown'),
	('Albert Camus'),
	('Fritjof Capra'),
	('Drew Conway'),
	('Jim Corbett'),
	('Thomas Cormen'),
	('Michael Crichton'),
	('William Dalrymple'),
	('Richard Dawkins'),
	('Siddhartha Deb'),
	('P L Deshpande'),
	('Sunita Deshpande'),
	('Keith Devlin'),
	('Charles Dickens'),
	('Peter Dickinson'),
	('Fyodor Dostoevsky'),
	('Allen Downey'),
	('Arthur Conan Doyle'),
	('Peter Drucker'),
	('Stephen Dubner'),
	('Hart Duda'),
	('Will Durant'),
	('Gerald Durrell'),
	('Bob Dylan'),
	('Steve Eddins'),
	('Abraham Eraly'),
	('Richard Feynman'),
	('Robert Fisk'),
	('Robert Fisk'),
	('Ken Follett'),
	('John Foreman'),
	('David Forsyth'),
	('Frederick Forsyth'),
	('Sergio Franco'),
	('Thomas Friedman'),
	('Earle Stanley Gardner'),
	('Sanjay Garg'),
	('Amitav Ghosh'),
	('James Gleick'),
	('Richard Gordon'),
	('Jaideva Goswami'),
	('W. H. Greene'),
	('John Grisham'),
	('Madan Gupta'),
	('Lorraine Hansberry'),
	('Sam Harris'),
	('Stephen Hawking'),
	('Simon Haykin'),
	('Werner Heisenberg'),
	('Joseph Heller'),
	('Ernest Hemingway'),
	('Victor Hugo'),
	('Samuel Huntington'),
	('Aldous Huxley'),
	('Lee Iacoca'),
	('Phillip Janert'),
	('Frank Kafka'),
	('V P Kale'),
	('Yashwant Kanetkar'),
	(' Kautiyla'),
	('Maria Konnikova'),
	('Dominique Lapierre'),
	('Steig Larsson'),
	(' Machiavelli'),
	('William S Maugham'),
	('Wes McKinney'),
	('V P Menon'),
	('Leonard Mlodinow'),
	('Ned Mohan'),
	('V S Naipaul'),
	(' Nariman'),
	('Kuldip Nayar'),
	('Jawaharlal Nehru'),
	('Robert Nisbet'),
	('Andy Oram'),
	('George Orwell'),
	(' Palkhivala'),
	(' Palkhivala'),
	('Randy Pausch'),
	('Robert Pirsig'),
	('Edgar Allen Poe'),
	('John Pratt'),
	('Ayn Rand'),
	('Sudhanshu Ranjan'),
	('Muhammad Rashid'),
	('Eric Raymond'),
	('J K Rowling'),
	('Bertrand Russell'),
	('Alex Rutherford'),
	('Carl Sagan'),
	('Edward Said'),
	('Jean Sassoon'),
	(' Sebastian Gutierrez'),
	('Amartya Sen'),
	('Frank Shih'),
	('Nate Silver'),
	('Simon Singh'),
	('Adam Smith'),
	(' Sorabjee'),
	('John Steinbeck'),
	('Alfred Stonier'),
	('Jonathan Stroud'),
	('Gerald Sussman'),
	('Andrew Tanenbaum'),
	('Terence Tao'),
	('Schilling Taub'),
	('Shashi Tharoor'),
	('Joy Thomas'),
	('Vladimir Vapnik'),
	(' Various'),
	('Jules Verne'),
	('Cedric Villani'),
	('Kurt Vonnegut'),
	('H G Wells'),
	('Morris West'),
	('Bob Woodward'),
	('Hussain Zaidi')
;

COMMIT;

